feat: Add typings to npm package
ethereum/solc-js pull request #693
Opened 2023-05-28 01:22 UTC by roninjin10

- add .d.ts files to final build with `declaration: true` in tsconfig 
- include .d.ts file in final tarball

2023-07-16 00:35 UTC, CoolColdUK commented
maybe need `types` in package.json as well?
<img width="501" alt="image" src="https://github.com/ethereum/solc-js/assets/35877983/858230d5-4c67-4d7a-afa2-a4186aaf2f76">

2023-09-11 08:12 UTC, yiyi-wang-rv commented
Any update to this PR? :eye:

2024-05-21 20:21 UTC, roninjin10 commented
Happy to help land this pr if any changes are requested

2025-01-07 20:57 UTC, OmarTawfik commented
Thank you for working on this. We are also running into this issue.

cc @r0qs for code review if you don't mind.

2025-03-04 11:35 UTC, r0qs requested changes
Thanks @roninjin10, and sorry for the very late reply, let's do this. Could you please just add the following:

```diff
--- i/package.json
+++ w/package.json
@@ -3,6 +3,7 @@
   "version": "0.8.28",
   "description": "Solidity compiler",
   "main": "index.js",
+  "types": "index.d.ts",
   "bin": {
     "solcjs": "solc.js"
   },
```
However, please note that this will not fully expose all types, as there is still some missing support that needs to be implemented: https://github.com/ethereum/solc-js/pull/615. Nevertheless, it is a step in the right direction, and I believe there is no harm in taking this as a first step.

2025-03-19 23:32 UTC, roninjin10 commented
I got some types here that I have been using past couple years for Tevm. Anyone is free to copy

https://github.com/evmts/tevm-monorepo/blob/main/bundler-packages/solc/src/solcTypes.ts

2025-03-19 23:32 UTC, roninjin10 commented
@r0qs I did your change happy to rebase or do any other changes you need

2025-03-21 10:16 UTC, r0qs commented
> @r0qs I did your change happy to rebase or do any other changes you need

Yes, could you please squash and rebase. :)

2025-04-22 21:23 UTC, roninjin10 commented
> > @r0qs I did your change happy to rebase or do any other changes you need
> 
> Yes, could you please squash and rebase. :)

Fresh rebase

2025-04-23 16:20 UTC, r0qs approved these changes

2025-04-23 17:05 UTC, roninjin10 commented on package.json
> +  "types": "index.d.ts",
You would normally also want exports array. Also sideEffect: false to enable tree shaking. Happy to follow up with a new pr cleaning this stuff up. They aren't critical but help provide universal compatibility to all tools

2025-04-29 10:06 UTC, r0qs commented on package.json
> +  "types": "index.d.ts",
Thanks, yes, that would be great :)

2025-04-29 10:06 UTC, merged